# -*- coding: cp1252 -*-
import sqlite3 as db


database = db.connect("pedidos.db")
cursor = database.cursor()

# listar tablas sqlite a.execute("SELECT * FROM sqlite_master WHERE type='table'")
#database.execute("CREATE TABLE CAJA  (idCAJA INTEGER PRIMARY KEY AUTOINCREMENT,  TOTAL INT NOT NULL, OTROSPAGOS INT NOT NULL, ENVIOS INT NOT NULL, FECHA TEXT NOT NULL)")
#
# creamos un campo unico entre los lotes y las manzanas, para evitar duplicidad.
#
# """CREATE TABLE CLIENTE (idCLIENTE INTEGER PRIMARY KEY AUTOINCREMENT , NUMERACIONOLOTE TEXT NOT NULL , CALLEOMANZANA TEXT NOT NULL , TELEFONO INT DEFAULT 0,
# BARRIO TEXT NOT NULL, EMPLEADO INT DEFAULT 0, idCARGOENVIO INT DEFAULT 0, FOREIGN KEY(idCARGOENVIO) REFERENCES DESCUENTO(idCARGOENVIO) UNIQUE(NUMERACIONOLOTE, CALLEOMANZANA))""")

#database.execute("CREATE TABLE PROMOCION  (idPROMO INTEGER PRIMARY KEY AUTOINCREMENT , PROMO TEXT NOT NULL, PRECIO INT NOT NULL)")

#database.execute("CREATE TABLE CARGOENVIO(idCARGOENVIO INTEGER PRIMARY KEY AUTOINCREMENT, BARRIO TEXT NOT NULL, PRECIO INT NOT NULL)")

# Se relacionan las tablas para crear un pedido.
# agregar fecha...


# database.execute("""CREATE TABLE PEDIDO (idPEDIDO INTEGER PRIMARY KEY AUTOINCREMENT, idPRODUCTO INT NOT NULL, CANTIDADPRODUCTO INT NOT NULL,
# idCLIENTE INT NOT NULL, ESTADO TEXT NOT NULL, TIPOENTREGA TEXT NOT NULL, idDESCUENTO INT DEFAULT 0, FECHA TEXT NOT NULL, 
# HORACREACION TEXT NOT NULL, FOREIGN KEY (idPRODUCTO) REFERENCES PRODUCTO(idPRODUCTO), 
# FOREIGN KEY (idCLIENTE) REFERENCES CLIENTE(idCLIENTE))""")
#
#
#"CREATE TABLE ASIENTOCONTABLE(idASIENTO INTEGER PRIMARY KEY AUTOINCREMENT, FECHA TEXT NOT NULL)"
#

#"CREATE TABLE CUENTA(idCUENTA INTEGER PRIMARY KEY AUTOINCREMENT, TIPOCUENTA TEXT NOT NULL, DEBE INT DEFAULT 0, HABER INT DEFAULT 0)"

#"CREATE TABLE MOVIMIENTOCONTABLE(idMOVIMIENTO INTEGER PRIMARY KEY AUTOINCREMENT, idASIENTO INT NOT NULL, idCUENTA INT NOT NULL, 
# DEBEOHABER INT DEFAULT 0, TIPOMOVIMIENTO TEXT NOT NULL, FOREIGN KEY (idASIENTO) REFERENCES ASIENTOCONTABLE(idASIENTO),
#  FOREIGN KEY (idCUENTA) REFERENCES CUENTA(idCUENTA))"
#

# mostramos solo los campos que relleno el usuario
# para eso debemos realizar una consulta.

# CONSULTA PARA MOSTRAR LOS PEDIDOS QUE SE REALIZAN:

# cursor.execute("SELECT pe.ROWID, m.MENU, b.BEBIDA, p.POSTRE, c.NOMBRES, c.APELLIDOS, c.TELEFONO,
# c.DIRECCION FROM PEDIDO pe INNER JOIN BEBIDA b ON pe.idBEBIDA = b.idBEBIDA INNER JOIN POSTRE p ON pe.idPOSTRE = p.idPOSTRE
# INNER JOIN CLIENTE c ON pe.idCLIENTE = c.idCLIENTE INNER JOIN MENU m ON pe.idMENU = m.idMENU WHERE pe.ESTADO='Preparado'")

#pedidos = cursor.execute("SELECT idCLIENTE, idMENU, idBEBIDA, idPOSTRE, TOTAL FROM PEDIDO")
#pedidos = pedidos.fecthall()

# cursor.execute("CREATE TABLE CLIENTE (idCLIENTE INTEGER PRIMARY KEY AUTOINCREMENT, NUMERACIONOLOTE TEXT NOT NULL, CALLEOMANZANA TEXT NOT NULL, TELEFONO INT NOT NULL, BARRIO TEXT NOT NULL)")


"""
cursor.execute("SELECT m.MENU, b.BEBIDA, p.POSTRE, c.NOMBRES, c.APELLIDOS, c.TELEFONO, c.DIRECCION FROM
PEDIDO pe INNER JOIN BEBIDA b ON pe.idBEBIDA = b.idBEBIDA INNER JOIN POSTRE o ON pe.idPOSTRE = p.idPOSTRE
INNER JOIN CLIENTE c ON pe.idCLIENTE = c.idCLIENTE")

#SE UNEN LAS TABLAS EN LA RELACION PEDIDO MOSTRANDO EL PEDIDO DEL CLIENTE:
cursor.execute("SELECT MENU,PRECIO,NOMBRES,APELLIDOS,TELEFONO,DIRECCION
               FROM MENU,CLIENTE,PEDIDO
               WHERE MENU.idMENU=PEDIDO.idMENU AND CLIENTE.idCLIENTE=PEDIDO.idCLIENTE")


ANALIZAR, RESOLVER:
NUESTRA BASE DE DATOS PEDIDO
"""

"""
la tabla productos contiene todos los productos a la venta, incluida las promociones.
"CREATE TABLE PRODUCTO (idPRODUCTO INTEGER PRIMARY KEY AUTOINCREMENT,
 PRODUCTO TEXT NOT NULL, DESCRIPCION TEXT NOT NULL, PRECIO INT NOT NULL, TIPOPRODUCTO TEXT NOT NULL)"

la tabla pedidos contiene todo lo relacionado a los productos, y el cliente.
 "CREATE TABLE PEDIDO (idPEDIDO INTEGER PRIMARY KEY AUTOINCREMENT, idPRODUCTO INT NOT NULL,
CANTIDADPRODUCTO INT NOT NULL, idCLIENTE INT NOT NULL, ESTADO TEXT NOT NULL, TIPOENTREGA TEXT NOT NULL,
FECHA TEXT NOT NULL, HORACREACION TEXT NOT NULL, FOREIGN KEY (idPRODUCTO) REFERENCES PRODUCTO(idPRODUCTO), 
FOREIGN KEY (idCLIENTE) REFERENCES CLIENTE(idCLIENTE))"
"""
